Demo_Role/Models/Employe.cs
using System;
using System.Collections.Generic;

namespace Demo_Role.Models
{
    public partial class Employe
    {
        public Employe()
        {
            EmployeRoles = new HashSet<EmployeRole>();
        }

        public int Id { get; set; }
        public string Password { get; set; } = null!;
        public DateTime? BirthDay { get; set; }
        public string? Adress { get; set; }
        public string? Email { get; set; }
        public int? Age { get; set; }
        public bool Gender { get; set; }
        public int GroupId { get; set; }
        public bool Status { get; set; }
        public int? IsSystem { get; set; }
        public string? UserName { get; set; }

        public virtual Group Group { get; set; } = null!;
        public virtual ICollection<EmployeRole> EmployeRoles { get; set; }
    }
}

Demo_Role/Controllers/EmployeController.cs
using Demo_Role.Constants;
using Demo_Role.CustomAuthorization;
using Demo_Role.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo_Role.Controllers
{
    public class EmployeController : Controller
    {
        [CustomAuthorize("Employe.Index")]
        public IActionResult Index()
        {
            return View();
        }
        private EmployessContext _db = new EmployessContext();



        [HttpGet]
        [CustomAuthorize("Employe.ShowDetail")]
        public async Task<IActionResult> ShowDetail()
        {
            var userEmail = HttpContext.Session.GetString(SessionConstants.EMAIL);
            if (string.IsNullOrEmpty(SessionConstants.EMAIL) || _db.Employes == null)
            {
                return NotFound();
            }

            var em = await _db.Employes
                .FirstOrDefaultAsync(m => m.Email == userEmail);
            if (em == null)
            {
                return NotFound();
            }


            return View(em);
        }


        [CustomAuthorize("Employe.Edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _db.Employes == null)
            {
                return NotFound();
            }

            var em = await _db.Employes.FindAsync(id)
;
            if (em == null)
            {
                return NotFound();
            }
            return View(em);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize("Employe.Edit")]
        public async Task<IActionResult> Edit(Employe employe)
        {
            var userEmail = HttpContext.Session.GetString(SessionConstants.EMAIL);
            if (userEmail == null)
            {
                return NotFound();
            }
            //if (id != employe.Id)
            //{
            //    return NotFound();
            //}
            if (userEmail != null){
                try
                {
                    _db.Employes.Update(employe);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployesExists(employe.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            } 
            return View(employe);
        }
        private bool EmployesExists(int id)
        {
            return _db.Employes.Any(e => e.Id == id);
        }

        public ActionResult Logout()
        {
            HttpContext.Session.Remove("Id");
            return RedirectToAction("Login", "Account");
        }
    }
}

Demo_Role/Views/Employe/Detail.cshtml
@model Demo_Role.Models.Employe

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>Employe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsSystem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsSystem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Demo_Role/Views/Employe/Edit.cshtml
@model Demo_Role.Models.Employe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Employe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDay" class="control-label"></label>
                <input asp-for="BirthDay" class="form-control" />
                <span asp-validation-for="BirthDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
               <select id="gender" name="Gender">
                      <option value="true">Nam</option>
                      <option value="false">Nu</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label"></label>
                <input hidden asp-for="GroupId" class="form-control" />
                <span asp-validation-for="GroupId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsSystem" /> @Html.DisplayNameFor(model => model.IsSystem)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ShowDetail">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Demo_Role/Views/Employe/Index.cshtml
@model Demo_Role.Models.Employe
<div>
    <h1>WelCome To Employes</h1> 
</div>
    <div class="text-center" >
         <a asp-controller="Employe" asp-action="ShowDetail">Details</a>
    </div>

    <div class="text-center" >
         <a asp-controller="Account" asp-action="Logout">logout</a>
    </div>

Demo_Role/Views/Employe/ShowDetail.cshtml
@model Demo_Role.Models.Employe

@{
    ViewData["Title"] = "ShowDetail";
}

<h1>ShowDetail</h1>

<div>
    <h4>Employe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> 
     <a asp-action="Index">Index</a>
</div>